--- 
title: "Mastering Shiny Book Club"
author: "The R4DS Online Learning Community"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: book.bib
biblio-style: apalike
link-citations: yes
github-repo: r4ds/bookclub-mshiny
description: "This website is the product of the R4DS Online Learning Community's Book Club."
---

# Welcome {-}

Welcome to the Mastering Shiny book club! 

the book [Mastering Shiny](https://mastering-shiny.org/) by Hadley Wickham.

-   These are **shared slides!**
    -   Developed by the [R4DS Online Learning Community](https://rfordatasci.com).
    -   [Join the community](https://r4ds.io/join) to participate.
    -   Available at [r4ds.io/mshiny](https://r4ds.io/mshiny).
-   We follow the [R4DS Online Learning Community Code of Conduct](https://r4ds.io/conduct).

## Pace {-}

-   Meet **every week.**
    -   Try to **always meet** even if no presenter available.
    -   Let the club know if there's a holiday, etc.
-   **1 chapter/week**
-   ...but split chapters if they feel like too much.

## Format {-}

-   **Volunteer to lead the discussion!** | [cohort 4](https://docs.google.com/spreadsheets/d/12b7L0jkMKC29vWqovVjoQKLVE1aB3YtIcu9lhWCGxI0/edit?usp=sharing) | [cohort 5](https://docs.google.com/spreadsheets/d/1VOKbxbxqZFDAv7bb9IHJK_W1IcKQeP_tgTuFj2O_r5w/edit?usp=sharing)
    -   **This is the best way to learn the material!**
-   Ideally **update shared slides**.
    -   Instructions in [github repo](https://github.com/r4ds/bookclub-mshiny).
    -   **Embedded code** is almost always easier to follow than live demos!
-   Presentations **recorded** & available on [**R4DS Online Learning Community YouTube Channel**](https://r4ds.io/youtube).
